version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: grocery-store-backend-postgres
    ports:
      - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ADMSTA
volumes:
  postgres-data:

